services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: yusr
      POSTGRES_PASSWORD: yusr
      POSTGRES_DB: yusr
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
