export const PERMISSIONS = {
  USERS_APPROVE: "users.approve",
  USERS_BAN: "users.ban",
  USERS_DEACTIVATE: "users.deactivate",
  STUDENTS_VIEW_ASSIGNED: "students.view_assigned",
  STUDENTS_VIEW_ALL: "students.view_all",
  STUDENTS_ASSIGN_GROUP: "students.assign_group",
  GROUPS_CREATE: "groups.create",
  GROUPS_UPDATE: "groups.update",
  SESSIONS_CREATE: "sessions.create",
  SESSIONS_START: "sessions.start",
  SESSIONS_GRADE: "sessions.grade",
  ASSIGNMENTS_CREATE: "assignments.create",
  ASSIGNMENTS_UPDATE: "assignments.update",
  EXAMS_CREATE: "exams.create",
  EXAMS_GRADE: "exams.grade",
  LEAVE_REQUESTS_REVIEW: "leave_requests.review",
  ANNOUNCEMENTS_CREATE: "announcements.create",
  NOTIFICATIONS_SEND: "notifications.send",
  SUPPORT_TICKETS_VIEW_ASSIGNED: "support_tickets.view_assigned",
  SUPPORT_TICKETS_VIEW_ALL: "support_tickets.view_all",
  SUPPORT_TICKETS_REPLY: "support_tickets.reply",
  SUPPORT_TICKETS_ESCALATE: "support_tickets.escalate",
  SYSTEM_SETTINGS_UPDATE: "system_settings.update",
  FEATURE_FLAGS_UPDATE: "feature_flags.update",
  AUDIT_LOGS_VIEW: "audit_logs.view",
  LEVELS_CREATE: "levels.create",
  LEVELS_UPDATE: "levels.update",
  CLASSES_CREATE: "classes.create",
  CLASSES_UPDATE: "classes.update",
  MODERATORS_ASSIGN: "moderators.assign",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  admin: Object.values(PERMISSIONS),
  moderator: [
    PERMISSIONS.STUDENTS_VIEW_ASSIGNED,
    PERMISSIONS.SESSIONS_CREATE,
    PERMISSIONS.SESSIONS_START,
    PERMISSIONS.SESSIONS_GRADE,
    PERMISSIONS.ASSIGNMENTS_CREATE,
    PERMISSIONS.ASSIGNMENTS_UPDATE,
    PERMISSIONS.EXAMS_CREATE,
    PERMISSIONS.EXAMS_GRADE,
    PERMISSIONS.LEAVE_REQUESTS_REVIEW,
  ],
  student: [],
  support: [
    PERMISSIONS.SUPPORT_TICKETS_VIEW_ASSIGNED,
    PERMISSIONS.SUPPORT_TICKETS_REPLY,
    PERMISSIONS.SUPPORT_TICKETS_ESCALATE,
  ],
};
